output "random_string" { value = random_string.random_string.id }
output "uuid" { value = random_uuid.uuid.result }
output "unixtime" { value = time_static.time.unix }
output "rfc3339_time" { value = time_static.time.rfc3339 }
output "account_id" { value = data.aws_caller_identity.current.account_id }
output "region" { value = data.aws_region.current.name }
output "partition" { value = data.aws_partition.current.id }
output "default_vpc_id" { value = data.aws_vpc.default.id }
output "internet_gateway_id" { value = data.aws_internet_gateway.default.id }
output "subnet_a_id" { value = data.aws_subnet.subnet_a.id }
output "subnet_a_az" { value = data.aws_subnet.subnet_a.availability_zone }
output "subnet_a_nacl_id"{ value = data.aws_network_acls.subnet_a.ids[0] }
output "subnet_a_cidr_block"{ value = data.aws_subnet.subnet_a.cidr_block }
output "subnet_b_id" { value = data.aws_subnet.subnet_b.id }
output "subnet_b_az" { value = data.aws_subnet.subnet_b.availability_zone }
output "subnet_b_nacl_id" { value = data.aws_network_acls.subnet_b.ids[0] }
output "subnet_b_cidr_block"{ value = data.aws_subnet.subnet_b.cidr_block }
output "amazon_linux_2_ami_id" { value = nonsensitive(data.aws_ssm_parameter.amazon_linux_2.value) }
output "amazon_linux_2023_ami_id" { value = nonsensitive(data.aws_ssm_parameter.amazon_linux_2023.value) }
output "key_pair_name" { value = data.aws_key_pair.student.key_name }
output "vpc_security_group_id" { value = data.aws_security_group.vpc_security_group.id }
